feature: share article through social links
BanklessDAO/bankless-dao-ghost-website pull request #98
Opened 2021-10-29 08:55 UTC by rixcian

I added functionality to social share links as described in #93 issue.

2021-10-30 20:59 UTC, zberwaldt commented on components/ShareLinks.tsx
> +import { Link, Flex, chakra, Icon, Box } from '@chakra-ui/react';
```suggestion
import { Link } from './Link';
```

2021-10-30 21:02 UTC, zberwaldt requested changes
In `components/ShareLinks.tsx` to use a wrapped link created by @jakeacooley.

2021-10-31 08:37 UTC, rixcian commented
@zberwaldt resolved

2021-12-11 03:02 UTC, zberwaldt approved these changes
Thank you. LGTM.

Thank you for all your work on this.

2021-12-11 03:04 UTC, merged